version: '2'

services:
    db:
        container_name: db
        image: mariadb
        restart: always
        volumes:
            - wikidb:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=password
    mwlib:
        container_name: mwlib
        image: mwlib:latest
        build:
            context: ./mwlib-docker
            #args:
            #    - http_proxy=http://proxy:port
            #    - https_proxy=http://proxy:port
        restart: always
        volumes:
            - wikidata:/config:ro
    wiki:
        container_name: wiki
        image: mediawiki:latest
        build:
            context: ./mediawiki-docker
            #args:
            #    - http_proxy=http://proxy:port
            #    - https_proxy=http://proxy:port
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - db
            - mwlib
        volumes:
            - wikidata:/data:rw
        environment:
            - MEDIAWIKI_VERSION=wmf/1.29.0-wmf.1
            - MEDIAWIKI_EXTENSIONS=CategoryTree ImageMap Collection
            - MEDIAWIKI_SITE_SERVER=https://192.168.1.1
            - MEDIAWIKI_RESTBASE_URL=https://192.168.1.1
            - MEDIAWIKI_SITE_NAME=MediaWiki
            - MEDIAWIKI_SITE_LANG=en
            - MEDIAWIKI_ADMIN_USER=admin
            - MEDIAWIKI_ADMIN_PASS=password
            - MEDIAWIKI_DB_TYPE=mysql
            - MEDIAWIKI_DB_HOST=db
            - MEDIAWIKI_DB_PORT=3306
            - MEDIAWIKI_DB_SCHEMA=mediawiki
            - MEDIAWIKI_DB_USER=root
            - MEDIAWIKI_DB_PASSWORD=password
            - MEDIAWIKI_DB_NAME=wikidb
            - MEDIAWIKI_ENABLE_SSL=true
            - MEDIAWIKI_UPDATE=true
            - MEDIAWIKI_MAX_UPLOAD_SIZE=209715200
volumes:
    wikidb:
        external:
            name: wikidb
    wikidata:
        external:
            name: wikidata
